/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Categorias implements Serializable
{
	/** 
	 * This attribute maps to the column ID_Categoria in the categorias table.
	 */
	protected int idCategoria;

	/** 
	 * This attribute maps to the column Nombre in the categorias table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column Activa in the categorias table.
	 */
	protected short activa;

	/** 
	 * This attribute maps to the column Pariente in the categorias table.
	 */
	protected int pariente;

	/**
	 * Method 'Categorias'
	 * 
	 */
	public Categorias()
	{
	}

	/**
	 * Method 'getIdCategoria'
	 * 
	 * @return int
	 */
	public int getIdCategoria()
	{
		return idCategoria;
	}

	/**
	 * Method 'setIdCategoria'
	 * 
	 * @param idCategoria
	 */
	public void setIdCategoria(int idCategoria)
	{
		this.idCategoria = idCategoria;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getActiva'
	 * 
	 * @return short
	 */
	public short getActiva()
	{
		return activa;
	}

	/**
	 * Method 'setActiva'
	 * 
	 * @param activa
	 */
	public void setActiva(short activa)
	{
		this.activa = activa;
	}

	/**
	 * Method 'getPariente'
	 * 
	 * @return int
	 */
	public int getPariente()
	{
		return pariente;
	}

	/**
	 * Method 'setPariente'
	 * 
	 * @param pariente
	 */
	public void setPariente(int pariente)
	{
		this.pariente = pariente;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Categorias)) {
			return false;
		}
		
		final Categorias _cast = (Categorias) _other;
		if (idCategoria != _cast.idCategoria) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (activa != _cast.activa) {
			return false;
		}
		
		if (pariente != _cast.pariente) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idCategoria;
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) activa;
		_hashCode = 29 * _hashCode + pariente;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CategoriasPk
	 */
	public CategoriasPk createPk()
	{
		return new CategoriasPk(idCategoria);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Categorias: " );
		ret.append( "idCategoria=" + idCategoria );
		ret.append( ", nombre=" + nombre );
		ret.append( ", activa=" + activa );
		ret.append( ", pariente=" + pariente );
		return ret.toString();
	}

}
