/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Cuenta implements Serializable
{
	/** 
	 * This attribute maps to the column Tipo_Documento in the cuenta table.
	 */
	protected String tipoDocumento;

	/** 
	 * This attribute maps to the column Numero_Documento in the cuenta table.
	 */
	protected String numeroDocumento;

	/** 
	 * This attribute maps to the column Primer_Nombre in the cuenta table.
	 */
	protected String primerNombre;

	/** 
	 * This attribute maps to the column Segundo_Nombre in the cuenta table.
	 */
	protected String segundoNombre;

	/** 
	 * This attribute maps to the column Primer_Apellido in the cuenta table.
	 */
	protected String primerApellido;

	/** 
	 * This attribute maps to the column Segundo_Apellido in the cuenta table.
	 */
	protected String segundoApellido;

	/** 
	 * This attribute maps to the column Contrasena in the cuenta table.
	 */
	protected String contrasena;

	/** 
	 * This attribute maps to the column Correo in the cuenta table.
	 */
	protected String correo;

	/** 
	 * This attribute maps to the column Direccion in the cuenta table.
	 */
	protected String direccion;

	/** 
	 * This attribute maps to the column Telefono in the cuenta table.
	 */
	protected String telefono;

	/** 
	 * This attribute maps to the column Rool in the cuenta table.
	 */
	protected String rool;

	/** 
	 * This attribute maps to the column Activo in the cuenta table.
	 */
	protected short activo;

	/** 
	 * This attribute maps to the column Ususario_idUsusario in the cuenta table.
	 */
	protected String ususarioIdususario;

	/**
	 * Method 'Cuenta'
	 * 
	 */
	public Cuenta()
	{
	}

	/**
	 * Method 'getTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/**
	 * Method 'setTipoDocumento'
	 * 
	 * @param tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
	}

	/**
	 * Method 'getNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'setNumeroDocumento'
	 * 
	 * @param numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * Method 'getPrimerNombre'
	 * 
	 * @return String
	 */
	public String getPrimerNombre()
	{
		return primerNombre;
	}

	/**
	 * Method 'setPrimerNombre'
	 * 
	 * @param primerNombre
	 */
	public void setPrimerNombre(String primerNombre)
	{
		this.primerNombre = primerNombre;
	}

	/**
	 * Method 'getSegundoNombre'
	 * 
	 * @return String
	 */
	public String getSegundoNombre()
	{
		return segundoNombre;
	}

	/**
	 * Method 'setSegundoNombre'
	 * 
	 * @param segundoNombre
	 */
	public void setSegundoNombre(String segundoNombre)
	{
		this.segundoNombre = segundoNombre;
	}

	/**
	 * Method 'getPrimerApellido'
	 * 
	 * @return String
	 */
	public String getPrimerApellido()
	{
		return primerApellido;
	}

	/**
	 * Method 'setPrimerApellido'
	 * 
	 * @param primerApellido
	 */
	public void setPrimerApellido(String primerApellido)
	{
		this.primerApellido = primerApellido;
	}

	/**
	 * Method 'getSegundoApellido'
	 * 
	 * @return String
	 */
	public String getSegundoApellido()
	{
		return segundoApellido;
	}

	/**
	 * Method 'setSegundoApellido'
	 * 
	 * @param segundoApellido
	 */
	public void setSegundoApellido(String segundoApellido)
	{
		this.segundoApellido = segundoApellido;
	}

	/**
	 * Method 'getContrasena'
	 * 
	 * @return String
	 */
	public String getContrasena()
	{
		return contrasena;
	}

	/**
	 * Method 'setContrasena'
	 * 
	 * @param contrasena
	 */
	public void setContrasena(String contrasena)
	{
		this.contrasena = contrasena;
	}

	/**
	 * Method 'getCorreo'
	 * 
	 * @return String
	 */
	public String getCorreo()
	{
		return correo;
	}

	/**
	 * Method 'setCorreo'
	 * 
	 * @param correo
	 */
	public void setCorreo(String correo)
	{
		this.correo = correo;
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
	}

	/**
	 * Method 'getRool'
	 * 
	 * @return String
	 */
	public String getRool()
	{
		return rool;
	}

	/**
	 * Method 'setRool'
	 * 
	 * @param rool
	 */
	public void setRool(String rool)
	{
		this.rool = rool;
	}

	/**
	 * Method 'getActivo'
	 * 
	 * @return short
	 */
	public short getActivo()
	{
		return activo;
	}

	/**
	 * Method 'setActivo'
	 * 
	 * @param activo
	 */
	public void setActivo(short activo)
	{
		this.activo = activo;
	}

	/**
	 * Method 'getUsusarioIdususario'
	 * 
	 * @return String
	 */
	public String getUsusarioIdususario()
	{
		return ususarioIdususario;
	}

	/**
	 * Method 'setUsusarioIdususario'
	 * 
	 * @param ususarioIdususario
	 */
	public void setUsusarioIdususario(String ususarioIdususario)
	{
		this.ususarioIdususario = ususarioIdususario;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Cuenta)) {
			return false;
		}
		
		final Cuenta _cast = (Cuenta) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (primerNombre == null ? _cast.primerNombre != primerNombre : !primerNombre.equals( _cast.primerNombre )) {
			return false;
		}
		
		if (segundoNombre == null ? _cast.segundoNombre != segundoNombre : !segundoNombre.equals( _cast.segundoNombre )) {
			return false;
		}
		
		if (primerApellido == null ? _cast.primerApellido != primerApellido : !primerApellido.equals( _cast.primerApellido )) {
			return false;
		}
		
		if (segundoApellido == null ? _cast.segundoApellido != segundoApellido : !segundoApellido.equals( _cast.segundoApellido )) {
			return false;
		}
		
		if (contrasena == null ? _cast.contrasena != contrasena : !contrasena.equals( _cast.contrasena )) {
			return false;
		}
		
		if (correo == null ? _cast.correo != correo : !correo.equals( _cast.correo )) {
			return false;
		}
		
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (rool == null ? _cast.rool != rool : !rool.equals( _cast.rool )) {
			return false;
		}
		
		if (activo != _cast.activo) {
			return false;
		}
		
		if (ususarioIdususario == null ? _cast.ususarioIdususario != ususarioIdususario : !ususarioIdususario.equals( _cast.ususarioIdususario )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		if (primerNombre != null) {
			_hashCode = 29 * _hashCode + primerNombre.hashCode();
		}
		
		if (segundoNombre != null) {
			_hashCode = 29 * _hashCode + segundoNombre.hashCode();
		}
		
		if (primerApellido != null) {
			_hashCode = 29 * _hashCode + primerApellido.hashCode();
		}
		
		if (segundoApellido != null) {
			_hashCode = 29 * _hashCode + segundoApellido.hashCode();
		}
		
		if (contrasena != null) {
			_hashCode = 29 * _hashCode + contrasena.hashCode();
		}
		
		if (correo != null) {
			_hashCode = 29 * _hashCode + correo.hashCode();
		}
		
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		if (rool != null) {
			_hashCode = 29 * _hashCode + rool.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) activo;
		if (ususarioIdususario != null) {
			_hashCode = 29 * _hashCode + ususarioIdususario.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CuentaPk
	 */
	public CuentaPk createPk()
	{
		return new CuentaPk(tipoDocumento, numeroDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Cuenta: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", primerNombre=" + primerNombre );
		ret.append( ", segundoNombre=" + segundoNombre );
		ret.append( ", primerApellido=" + primerApellido );
		ret.append( ", segundoApellido=" + segundoApellido );
		ret.append( ", contrasena=" + contrasena );
		ret.append( ", correo=" + correo );
		ret.append( ", direccion=" + direccion );
		ret.append( ", telefono=" + telefono );
		ret.append( ", rool=" + rool );
		ret.append( ", activo=" + activo );
		ret.append( ", ususarioIdususario=" + ususarioIdususario );
		return ret.toString();
	}

}
