/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Domicilio implements Serializable
{
	/** 
	 * This attribute maps to the column Municipio_idMunicipio in the domicilio table.
	 */
	protected String municipioIdmunicipio;

	/** 
	 * This attribute maps to the column Cuenta_Tipo_Documento in the domicilio table.
	 */
	protected String cuentaTipoDocumento;

	/** 
	 * This attribute maps to the column Cuenta_Numero_Documento in the domicilio table.
	 */
	protected String cuentaNumeroDocumento;

	/** 
	 * This attribute maps to the column Ciudad in the domicilio table.
	 */
	protected String ciudad;

	/** 
	 * This attribute maps to the column Direccion in the domicilio table.
	 */
	protected String direccion;

	/** 
	 * This attribute maps to the column Telefono in the domicilio table.
	 */
	protected String telefono;

	/**
	 * Method 'Domicilio'
	 * 
	 */
	public Domicilio()
	{
	}

	/**
	 * Method 'getMunicipioIdmunicipio'
	 * 
	 * @return String
	 */
	public String getMunicipioIdmunicipio()
	{
		return municipioIdmunicipio;
	}

	/**
	 * Method 'setMunicipioIdmunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public void setMunicipioIdmunicipio(String municipioIdmunicipio)
	{
		this.municipioIdmunicipio = municipioIdmunicipio;
	}

	/**
	 * Method 'getCuentaTipoDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipoDocumento()
	{
		return cuentaTipoDocumento;
	}

	/**
	 * Method 'setCuentaTipoDocumento'
	 * 
	 * @param cuentaTipoDocumento
	 */
	public void setCuentaTipoDocumento(String cuentaTipoDocumento)
	{
		this.cuentaTipoDocumento = cuentaTipoDocumento;
	}

	/**
	 * Method 'getCuentaNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumeroDocumento()
	{
		return cuentaNumeroDocumento;
	}

	/**
	 * Method 'setCuentaNumeroDocumento'
	 * 
	 * @param cuentaNumeroDocumento
	 */
	public void setCuentaNumeroDocumento(String cuentaNumeroDocumento)
	{
		this.cuentaNumeroDocumento = cuentaNumeroDocumento;
	}

	/**
	 * Method 'getCiudad'
	 * 
	 * @return String
	 */
	public String getCiudad()
	{
		return ciudad;
	}

	/**
	 * Method 'setCiudad'
	 * 
	 * @param ciudad
	 */
	public void setCiudad(String ciudad)
	{
		this.ciudad = ciudad;
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Domicilio)) {
			return false;
		}
		
		final Domicilio _cast = (Domicilio) _other;
		if (municipioIdmunicipio == null ? _cast.municipioIdmunicipio != municipioIdmunicipio : !municipioIdmunicipio.equals( _cast.municipioIdmunicipio )) {
			return false;
		}
		
		if (cuentaTipoDocumento == null ? _cast.cuentaTipoDocumento != cuentaTipoDocumento : !cuentaTipoDocumento.equals( _cast.cuentaTipoDocumento )) {
			return false;
		}
		
		if (cuentaNumeroDocumento == null ? _cast.cuentaNumeroDocumento != cuentaNumeroDocumento : !cuentaNumeroDocumento.equals( _cast.cuentaNumeroDocumento )) {
			return false;
		}
		
		if (ciudad == null ? _cast.ciudad != ciudad : !ciudad.equals( _cast.ciudad )) {
			return false;
		}
		
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (municipioIdmunicipio != null) {
			_hashCode = 29 * _hashCode + municipioIdmunicipio.hashCode();
		}
		
		if (cuentaTipoDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipoDocumento.hashCode();
		}
		
		if (cuentaNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumeroDocumento.hashCode();
		}
		
		if (ciudad != null) {
			_hashCode = 29 * _hashCode + ciudad.hashCode();
		}
		
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DomicilioPk
	 */
	public DomicilioPk createPk()
	{
		return new DomicilioPk(cuentaTipoDocumento, cuentaNumeroDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Domicilio: " );
		ret.append( "municipioIdmunicipio=" + municipioIdmunicipio );
		ret.append( ", cuentaTipoDocumento=" + cuentaTipoDocumento );
		ret.append( ", cuentaNumeroDocumento=" + cuentaNumeroDocumento );
		ret.append( ", ciudad=" + ciudad );
		ret.append( ", direccion=" + direccion );
		ret.append( ", telefono=" + telefono );
		return ret.toString();
	}

}
