/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ItemsDelCarrito implements Serializable
{
	/** 
	 * This attribute maps to the column Producto_ID_producto in the items_del_carrito table.
	 */
	protected String productoIdProducto;

	/** 
	 * This attribute maps to the column Cantidad in the items_del_carrito table.
	 */
	protected int cantidad;

	/** 
	 * This attribute maps to the column Costo_Unitario in the items_del_carrito table.
	 */
	protected float costoUnitario;

	/** 
	 * This attribute maps to the column Costo_Total in the items_del_carrito table.
	 */
	protected float costoTotal;

	/** 
	 * This attribute maps to the column Carrito_De_Compras_ID_Carrito in the items_del_carrito table.
	 */
	protected String carritoDeComprasIdCarrito;

	/**
	 * Method 'ItemsDelCarrito'
	 * 
	 */
	public ItemsDelCarrito()
	{
	}

	/**
	 * Method 'getProductoIdProducto'
	 * 
	 * @return String
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'setProductoIdProducto'
	 * 
	 * @param productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
	}

	/**
	 * Method 'getCostoUnitario'
	 * 
	 * @return float
	 */
	public float getCostoUnitario()
	{
		return costoUnitario;
	}

	/**
	 * Method 'setCostoUnitario'
	 * 
	 * @param costoUnitario
	 */
	public void setCostoUnitario(float costoUnitario)
	{
		this.costoUnitario = costoUnitario;
	}

	/**
	 * Method 'getCostoTotal'
	 * 
	 * @return float
	 */
	public float getCostoTotal()
	{
		return costoTotal;
	}

	/**
	 * Method 'setCostoTotal'
	 * 
	 * @param costoTotal
	 */
	public void setCostoTotal(float costoTotal)
	{
		this.costoTotal = costoTotal;
	}

	/**
	 * Method 'getCarritoDeComprasIdCarrito'
	 * 
	 * @return String
	 */
	public String getCarritoDeComprasIdCarrito()
	{
		return carritoDeComprasIdCarrito;
	}

	/**
	 * Method 'setCarritoDeComprasIdCarrito'
	 * 
	 * @param carritoDeComprasIdCarrito
	 */
	public void setCarritoDeComprasIdCarrito(String carritoDeComprasIdCarrito)
	{
		this.carritoDeComprasIdCarrito = carritoDeComprasIdCarrito;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemsDelCarrito)) {
			return false;
		}
		
		final ItemsDelCarrito _cast = (ItemsDelCarrito) _other;
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (costoUnitario != _cast.costoUnitario) {
			return false;
		}
		
		if (costoTotal != _cast.costoTotal) {
			return false;
		}
		
		if (carritoDeComprasIdCarrito == null ? _cast.carritoDeComprasIdCarrito != carritoDeComprasIdCarrito : !carritoDeComprasIdCarrito.equals( _cast.carritoDeComprasIdCarrito )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + Float.floatToIntBits(costoUnitario);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(costoTotal);
		if (carritoDeComprasIdCarrito != null) {
			_hashCode = 29 * _hashCode + carritoDeComprasIdCarrito.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemsDelCarritoPk
	 */
	public ItemsDelCarritoPk createPk()
	{
		return new ItemsDelCarritoPk(productoIdProducto, carritoDeComprasIdCarrito);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.ItemsDelCarrito: " );
		ret.append( "productoIdProducto=" + productoIdProducto );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", costoUnitario=" + costoUnitario );
		ret.append( ", costoTotal=" + costoTotal );
		ret.append( ", carritoDeComprasIdCarrito=" + carritoDeComprasIdCarrito );
		return ret.toString();
	}

}
