/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Item implements Serializable
{
	/** 
	 * This attribute maps to the column Producto_ID_producto in the item table.
	 */
	protected String productoIdProducto;

	/** 
	 * This attribute maps to the column Pedido_Factura_ID_Factura in the item table.
	 */
	protected int pedidoFacturaIdFactura;

	/** 
	 * This attribute maps to the column Cantidad in the item table.
	 */
	protected int cantidad;

	/** 
	 * This attribute maps to the column Costo_Total in the item table.
	 */
	protected float costoTotal;

	/** 
	 * This attribute maps to the column Costo_Unitario in the item table.
	 */
	protected float costoUnitario;

	/**
	 * Method 'Item'
	 * 
	 */
	public Item()
	{
	}

	/**
	 * Method 'getProductoIdProducto'
	 * 
	 * @return String
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'setProductoIdProducto'
	 * 
	 * @param productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
	}

	/**
	 * Method 'getPedidoFacturaIdFactura'
	 * 
	 * @return int
	 */
	public int getPedidoFacturaIdFactura()
	{
		return pedidoFacturaIdFactura;
	}

	/**
	 * Method 'setPedidoFacturaIdFactura'
	 * 
	 * @param pedidoFacturaIdFactura
	 */
	public void setPedidoFacturaIdFactura(int pedidoFacturaIdFactura)
	{
		this.pedidoFacturaIdFactura = pedidoFacturaIdFactura;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
	}

	/**
	 * Method 'getCostoTotal'
	 * 
	 * @return float
	 */
	public float getCostoTotal()
	{
		return costoTotal;
	}

	/**
	 * Method 'setCostoTotal'
	 * 
	 * @param costoTotal
	 */
	public void setCostoTotal(float costoTotal)
	{
		this.costoTotal = costoTotal;
	}

	/**
	 * Method 'getCostoUnitario'
	 * 
	 * @return float
	 */
	public float getCostoUnitario()
	{
		return costoUnitario;
	}

	/**
	 * Method 'setCostoUnitario'
	 * 
	 * @param costoUnitario
	 */
	public void setCostoUnitario(float costoUnitario)
	{
		this.costoUnitario = costoUnitario;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Item)) {
			return false;
		}
		
		final Item _cast = (Item) _other;
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (pedidoFacturaIdFactura != _cast.pedidoFacturaIdFactura) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (costoTotal != _cast.costoTotal) {
			return false;
		}
		
		if (costoUnitario != _cast.costoUnitario) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + pedidoFacturaIdFactura;
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + Float.floatToIntBits(costoTotal);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(costoUnitario);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemPk
	 */
	public ItemPk createPk()
	{
		return new ItemPk(productoIdProducto, pedidoFacturaIdFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Item: " );
		ret.append( "productoIdProducto=" + productoIdProducto );
		ret.append( ", pedidoFacturaIdFactura=" + pedidoFacturaIdFactura );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", costoTotal=" + costoTotal );
		ret.append( ", costoUnitario=" + costoUnitario );
		return ret.toString();
	}

}
