/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.negocio.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.akuavida.integracion.dao.CarritoDeComprasDao;
import edu.co.sena.akuavida.integracion.dto.CarritoDeCompras;
import edu.co.sena.akuavida.integracion.exceptions.CarritoDeComprasDaoException;
import edu.co.sena.akuavida.integracion.factory.CarritoDeComprasDaoFactory;

public class CarritoDeComprasDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdCarritoEquals("");
		// findWhereTotalEquals(0);
		// findWhereSubtotalEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CarritoDeComprasDao _dao = getCarritoDeComprasDao();
			CarritoDeCompras _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdCarritoEquals'
	 * 
	 * @param idCarrito
	 */
	public static void findWhereIdCarritoEquals(String idCarrito)
	{
		try {
			CarritoDeComprasDao _dao = getCarritoDeComprasDao();
			CarritoDeCompras _result[] = _dao.findWhereIdCarritoEquals(idCarrito);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTotalEquals'
	 * 
	 * @param total
	 */
	public static void findWhereTotalEquals(float total)
	{
		try {
			CarritoDeComprasDao _dao = getCarritoDeComprasDao();
			CarritoDeCompras _result[] = _dao.findWhereTotalEquals(total);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSubtotalEquals'
	 * 
	 * @param subtotal
	 */
	public static void findWhereSubtotalEquals(float subtotal)
	{
		try {
			CarritoDeComprasDao _dao = getCarritoDeComprasDao();
			CarritoDeCompras _result[] = _dao.findWhereSubtotalEquals(subtotal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCarritoDeComprasDao'
	 * 
	 * @return CarritoDeComprasDao
	 */
	public static CarritoDeComprasDao getCarritoDeComprasDao()
	{
		return CarritoDeComprasDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(CarritoDeCompras dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdCarrito() );
		buf.append( ", " );
		buf.append( dto.getTotal() );
		buf.append( ", " );
		buf.append( dto.getSubtotal() );
		System.out.println( buf.toString() );
	}

}
