/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.negocio.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.akuavida.integracion.dao.CuentaDao;
import edu.co.sena.akuavida.integracion.dto.Cuenta;
import edu.co.sena.akuavida.integracion.exceptions.CuentaDaoException;
import edu.co.sena.akuavida.integracion.factory.CuentaDaoFactory;

public class CuentaDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByUsusario("");
		// findWhereTipoDocumentoEquals("");
		// findWhereNumeroDocumentoEquals("");
		// findWherePrimerNombreEquals("");
		// findWhereSegundoNombreEquals("");
		// findWherePrimerApellidoEquals("");
		// findWhereSegundoApellidoEquals("");
		// findWhereContrasenaEquals("");
		// findWhereCorreoEquals("");
		// findWhereDireccionEquals("");
		// findWhereTelefonoEquals("");
		// findWhereRoolEquals("");
		// findWhereActivoEquals(0);
		// findWhereUsusarioIdususarioEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUsusario'
	 * 
	 * @param ususarioIdususario
	 */
	public static void findByUsusario(String ususarioIdususario)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findByUsusario(ususarioIdususario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTipoDocumentoEquals'
	 * 
	 * @param tipoDocumento
	 */
	public static void findWhereTipoDocumentoEquals(String tipoDocumento)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereTipoDocumentoEquals(tipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumeroDocumentoEquals'
	 * 
	 * @param numeroDocumento
	 */
	public static void findWhereNumeroDocumentoEquals(String numeroDocumento)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereNumeroDocumentoEquals(numeroDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrimerNombreEquals'
	 * 
	 * @param primerNombre
	 */
	public static void findWherePrimerNombreEquals(String primerNombre)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWherePrimerNombreEquals(primerNombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSegundoNombreEquals'
	 * 
	 * @param segundoNombre
	 */
	public static void findWhereSegundoNombreEquals(String segundoNombre)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereSegundoNombreEquals(segundoNombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrimerApellidoEquals'
	 * 
	 * @param primerApellido
	 */
	public static void findWherePrimerApellidoEquals(String primerApellido)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWherePrimerApellidoEquals(primerApellido);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSegundoApellidoEquals'
	 * 
	 * @param segundoApellido
	 */
	public static void findWhereSegundoApellidoEquals(String segundoApellido)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereSegundoApellidoEquals(segundoApellido);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereContrasenaEquals'
	 * 
	 * @param contrasena
	 */
	public static void findWhereContrasenaEquals(String contrasena)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereContrasenaEquals(contrasena);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorreoEquals'
	 * 
	 * @param correo
	 */
	public static void findWhereCorreoEquals(String correo)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereCorreoEquals(correo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDireccionEquals'
	 * 
	 * @param direccion
	 */
	public static void findWhereDireccionEquals(String direccion)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereDireccionEquals(direccion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTelefonoEquals'
	 * 
	 * @param telefono
	 */
	public static void findWhereTelefonoEquals(String telefono)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereTelefonoEquals(telefono);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRoolEquals'
	 * 
	 * @param rool
	 */
	public static void findWhereRoolEquals(String rool)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereRoolEquals(rool);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereActivoEquals'
	 * 
	 * @param activo
	 */
	public static void findWhereActivoEquals(short activo)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereActivoEquals(activo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUsusarioIdususarioEquals'
	 * 
	 * @param ususarioIdususario
	 */
	public static void findWhereUsusarioIdususarioEquals(String ususarioIdususario)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereUsusarioIdususarioEquals(ususarioIdususario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCuentaDao'
	 * 
	 * @return CuentaDao
	 */
	public static CuentaDao getCuentaDao()
	{
		return CuentaDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Cuenta dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getTipoDocumento() );
		buf.append( ", " );
		buf.append( dto.getNumeroDocumento() );
		buf.append( ", " );
		buf.append( dto.getPrimerNombre() );
		buf.append( ", " );
		buf.append( dto.getSegundoNombre() );
		buf.append( ", " );
		buf.append( dto.getPrimerApellido() );
		buf.append( ", " );
		buf.append( dto.getSegundoApellido() );
		buf.append( ", " );
		buf.append( dto.getContrasena() );
		buf.append( ", " );
		buf.append( dto.getCorreo() );
		buf.append( ", " );
		buf.append( dto.getDireccion() );
		buf.append( ", " );
		buf.append( dto.getTelefono() );
		buf.append( ", " );
		buf.append( dto.getRool() );
		buf.append( ", " );
		buf.append( dto.getActivo() );
		buf.append( ", " );
		buf.append( dto.getUsusarioIdususario() );
		System.out.println( buf.toString() );
	}

}
