/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.negocio.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.akuavida.integracion.dao.InventarioDao;
import edu.co.sena.akuavida.integracion.dto.Inventario;
import edu.co.sena.akuavida.integracion.exceptions.InventarioDaoException;
import edu.co.sena.akuavida.integracion.factory.InventarioDaoFactory;

public class InventarioDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByProducto("");
		// findWhereIdInventarioEquals(0);
		// findWhereCantidadEquals(0);
		// findWhereProductoIdProductoEquals("");
		// findWhereCantidadProductoCompradoEquals(0);
		// findWhereFechaDeCompraEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			InventarioDao _dao = getInventarioDao();
			Inventario _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByProducto'
	 * 
	 * @param productoIdProducto
	 */
	public static void findByProducto(String productoIdProducto)
	{
		try {
			InventarioDao _dao = getInventarioDao();
			Inventario _result[] = _dao.findByProducto(productoIdProducto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdInventarioEquals'
	 * 
	 * @param idInventario
	 */
	public static void findWhereIdInventarioEquals(int idInventario)
	{
		try {
			InventarioDao _dao = getInventarioDao();
			Inventario _result[] = _dao.findWhereIdInventarioEquals(idInventario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCantidadEquals'
	 * 
	 * @param cantidad
	 */
	public static void findWhereCantidadEquals(int cantidad)
	{
		try {
			InventarioDao _dao = getInventarioDao();
			Inventario _result[] = _dao.findWhereCantidadEquals(cantidad);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductoIdProductoEquals'
	 * 
	 * @param productoIdProducto
	 */
	public static void findWhereProductoIdProductoEquals(String productoIdProducto)
	{
		try {
			InventarioDao _dao = getInventarioDao();
			Inventario _result[] = _dao.findWhereProductoIdProductoEquals(productoIdProducto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCantidadProductoCompradoEquals'
	 * 
	 * @param cantidadProductoComprado
	 */
	public static void findWhereCantidadProductoCompradoEquals(float cantidadProductoComprado)
	{
		try {
			InventarioDao _dao = getInventarioDao();
			Inventario _result[] = _dao.findWhereCantidadProductoCompradoEquals(cantidadProductoComprado);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaDeCompraEquals'
	 * 
	 * @param fechaDeCompra
	 */
	public static void findWhereFechaDeCompraEquals(Date fechaDeCompra)
	{
		try {
			InventarioDao _dao = getInventarioDao();
			Inventario _result[] = _dao.findWhereFechaDeCompraEquals(fechaDeCompra);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getInventarioDao'
	 * 
	 * @return InventarioDao
	 */
	public static InventarioDao getInventarioDao()
	{
		return InventarioDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Inventario dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdInventario() );
		buf.append( ", " );
		buf.append( dto.getCantidad() );
		buf.append( ", " );
		buf.append( dto.getProductoIdProducto() );
		buf.append( ", " );
		buf.append( dto.getCantidadProductoComprado() );
		buf.append( ", " );
		buf.append( dto.getFechaDeCompra() );
		System.out.println( buf.toString() );
	}

}
