/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Cuenta implements Serializable
{
	/** 
	 * This attribute maps to the column Tipo_Documento in the cuenta table.
	 */
	protected String tipoDocumento;

	/** 
	 * This attribute represents whether the attribute tipoDocumento has been modified since being read from the database.
	 */
	protected boolean tipoDocumentoModified = false;

	/** 
	 * This attribute maps to the column Numero_Documento in the cuenta table.
	 */
	protected String numeroDocumento;

	/** 
	 * This attribute represents whether the attribute numeroDocumento has been modified since being read from the database.
	 */
	protected boolean numeroDocumentoModified = false;

	/** 
	 * This attribute maps to the column Primer_Nombre in the cuenta table.
	 */
	protected String primerNombre;

	/** 
	 * This attribute represents whether the attribute primerNombre has been modified since being read from the database.
	 */
	protected boolean primerNombreModified = false;

	/** 
	 * This attribute maps to the column Segundo_Nombre in the cuenta table.
	 */
	protected String segundoNombre;

	/** 
	 * This attribute represents whether the attribute segundoNombre has been modified since being read from the database.
	 */
	protected boolean segundoNombreModified = false;

	/** 
	 * This attribute maps to the column Primer_Apellido in the cuenta table.
	 */
	protected String primerApellido;

	/** 
	 * This attribute represents whether the attribute primerApellido has been modified since being read from the database.
	 */
	protected boolean primerApellidoModified = false;

	/** 
	 * This attribute maps to the column Segundo_Apellido in the cuenta table.
	 */
	protected String segundoApellido;

	/** 
	 * This attribute represents whether the attribute segundoApellido has been modified since being read from the database.
	 */
	protected boolean segundoApellidoModified = false;

	/** 
	 * This attribute maps to the column Contrasena in the cuenta table.
	 */
	protected String contrasena;

	/** 
	 * This attribute represents whether the attribute contrasena has been modified since being read from the database.
	 */
	protected boolean contrasenaModified = false;

	/** 
	 * This attribute maps to the column Correo in the cuenta table.
	 */
	protected String correo;

	/** 
	 * This attribute represents whether the attribute correo has been modified since being read from the database.
	 */
	protected boolean correoModified = false;

	/** 
	 * This attribute maps to the column Direccion in the cuenta table.
	 */
	protected String direccion;

	/** 
	 * This attribute represents whether the attribute direccion has been modified since being read from the database.
	 */
	protected boolean direccionModified = false;

	/** 
	 * This attribute maps to the column Telefono in the cuenta table.
	 */
	protected String telefono;

	/** 
	 * This attribute represents whether the attribute telefono has been modified since being read from the database.
	 */
	protected boolean telefonoModified = false;

	/** 
	 * This attribute maps to the column Rool in the cuenta table.
	 */
	protected String rool;

	/** 
	 * This attribute represents whether the attribute rool has been modified since being read from the database.
	 */
	protected boolean roolModified = false;

	/** 
	 * This attribute maps to the column Activo in the cuenta table.
	 */
	protected short activo;

	/** 
	 * This attribute represents whether the attribute activo has been modified since being read from the database.
	 */
	protected boolean activoModified = false;

	/** 
	 * This attribute maps to the column Ususario_idUsusario in the cuenta table.
	 */
	protected String ususarioIdususario;

	/** 
	 * This attribute represents whether the attribute ususarioIdususario has been modified since being read from the database.
	 */
	protected boolean ususarioIdususarioModified = false;

	/**
	 * Method 'Cuenta'
	 * 
	 */
	public Cuenta()
	{
	}

	/**
	 * Method 'getTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/**
	 * Method 'setTipoDocumento'
	 * 
	 * @param tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
		this.tipoDocumentoModified = true;
	}

	/** 
	 * Sets the value of tipoDocumentoModified
	 */
	public void setTipoDocumentoModified(boolean tipoDocumentoModified)
	{
		this.tipoDocumentoModified = tipoDocumentoModified;
	}

	/** 
	 * Gets the value of tipoDocumentoModified
	 */
	public boolean isTipoDocumentoModified()
	{
		return tipoDocumentoModified;
	}

	/**
	 * Method 'getNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'setNumeroDocumento'
	 * 
	 * @param numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
		this.numeroDocumentoModified = true;
	}

	/** 
	 * Sets the value of numeroDocumentoModified
	 */
	public void setNumeroDocumentoModified(boolean numeroDocumentoModified)
	{
		this.numeroDocumentoModified = numeroDocumentoModified;
	}

	/** 
	 * Gets the value of numeroDocumentoModified
	 */
	public boolean isNumeroDocumentoModified()
	{
		return numeroDocumentoModified;
	}

	/**
	 * Method 'getPrimerNombre'
	 * 
	 * @return String
	 */
	public String getPrimerNombre()
	{
		return primerNombre;
	}

	/**
	 * Method 'setPrimerNombre'
	 * 
	 * @param primerNombre
	 */
	public void setPrimerNombre(String primerNombre)
	{
		this.primerNombre = primerNombre;
		this.primerNombreModified = true;
	}

	/** 
	 * Sets the value of primerNombreModified
	 */
	public void setPrimerNombreModified(boolean primerNombreModified)
	{
		this.primerNombreModified = primerNombreModified;
	}

	/** 
	 * Gets the value of primerNombreModified
	 */
	public boolean isPrimerNombreModified()
	{
		return primerNombreModified;
	}

	/**
	 * Method 'getSegundoNombre'
	 * 
	 * @return String
	 */
	public String getSegundoNombre()
	{
		return segundoNombre;
	}

	/**
	 * Method 'setSegundoNombre'
	 * 
	 * @param segundoNombre
	 */
	public void setSegundoNombre(String segundoNombre)
	{
		this.segundoNombre = segundoNombre;
		this.segundoNombreModified = true;
	}

	/** 
	 * Sets the value of segundoNombreModified
	 */
	public void setSegundoNombreModified(boolean segundoNombreModified)
	{
		this.segundoNombreModified = segundoNombreModified;
	}

	/** 
	 * Gets the value of segundoNombreModified
	 */
	public boolean isSegundoNombreModified()
	{
		return segundoNombreModified;
	}

	/**
	 * Method 'getPrimerApellido'
	 * 
	 * @return String
	 */
	public String getPrimerApellido()
	{
		return primerApellido;
	}

	/**
	 * Method 'setPrimerApellido'
	 * 
	 * @param primerApellido
	 */
	public void setPrimerApellido(String primerApellido)
	{
		this.primerApellido = primerApellido;
		this.primerApellidoModified = true;
	}

	/** 
	 * Sets the value of primerApellidoModified
	 */
	public void setPrimerApellidoModified(boolean primerApellidoModified)
	{
		this.primerApellidoModified = primerApellidoModified;
	}

	/** 
	 * Gets the value of primerApellidoModified
	 */
	public boolean isPrimerApellidoModified()
	{
		return primerApellidoModified;
	}

	/**
	 * Method 'getSegundoApellido'
	 * 
	 * @return String
	 */
	public String getSegundoApellido()
	{
		return segundoApellido;
	}

	/**
	 * Method 'setSegundoApellido'
	 * 
	 * @param segundoApellido
	 */
	public void setSegundoApellido(String segundoApellido)
	{
		this.segundoApellido = segundoApellido;
		this.segundoApellidoModified = true;
	}

	/** 
	 * Sets the value of segundoApellidoModified
	 */
	public void setSegundoApellidoModified(boolean segundoApellidoModified)
	{
		this.segundoApellidoModified = segundoApellidoModified;
	}

	/** 
	 * Gets the value of segundoApellidoModified
	 */
	public boolean isSegundoApellidoModified()
	{
		return segundoApellidoModified;
	}

	/**
	 * Method 'getContrasena'
	 * 
	 * @return String
	 */
	public String getContrasena()
	{
		return contrasena;
	}

	/**
	 * Method 'setContrasena'
	 * 
	 * @param contrasena
	 */
	public void setContrasena(String contrasena)
	{
		this.contrasena = contrasena;
		this.contrasenaModified = true;
	}

	/** 
	 * Sets the value of contrasenaModified
	 */
	public void setContrasenaModified(boolean contrasenaModified)
	{
		this.contrasenaModified = contrasenaModified;
	}

	/** 
	 * Gets the value of contrasenaModified
	 */
	public boolean isContrasenaModified()
	{
		return contrasenaModified;
	}

	/**
	 * Method 'getCorreo'
	 * 
	 * @return String
	 */
	public String getCorreo()
	{
		return correo;
	}

	/**
	 * Method 'setCorreo'
	 * 
	 * @param correo
	 */
	public void setCorreo(String correo)
	{
		this.correo = correo;
		this.correoModified = true;
	}

	/** 
	 * Sets the value of correoModified
	 */
	public void setCorreoModified(boolean correoModified)
	{
		this.correoModified = correoModified;
	}

	/** 
	 * Gets the value of correoModified
	 */
	public boolean isCorreoModified()
	{
		return correoModified;
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
		this.direccionModified = true;
	}

	/** 
	 * Sets the value of direccionModified
	 */
	public void setDireccionModified(boolean direccionModified)
	{
		this.direccionModified = direccionModified;
	}

	/** 
	 * Gets the value of direccionModified
	 */
	public boolean isDireccionModified()
	{
		return direccionModified;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
		this.telefonoModified = true;
	}

	/** 
	 * Sets the value of telefonoModified
	 */
	public void setTelefonoModified(boolean telefonoModified)
	{
		this.telefonoModified = telefonoModified;
	}

	/** 
	 * Gets the value of telefonoModified
	 */
	public boolean isTelefonoModified()
	{
		return telefonoModified;
	}

	/**
	 * Method 'getRool'
	 * 
	 * @return String
	 */
	public String getRool()
	{
		return rool;
	}

	/**
	 * Method 'setRool'
	 * 
	 * @param rool
	 */
	public void setRool(String rool)
	{
		this.rool = rool;
		this.roolModified = true;
	}

	/** 
	 * Sets the value of roolModified
	 */
	public void setRoolModified(boolean roolModified)
	{
		this.roolModified = roolModified;
	}

	/** 
	 * Gets the value of roolModified
	 */
	public boolean isRoolModified()
	{
		return roolModified;
	}

	/**
	 * Method 'getActivo'
	 * 
	 * @return short
	 */
	public short getActivo()
	{
		return activo;
	}

	/**
	 * Method 'setActivo'
	 * 
	 * @param activo
	 */
	public void setActivo(short activo)
	{
		this.activo = activo;
		this.activoModified = true;
	}

	/** 
	 * Sets the value of activoModified
	 */
	public void setActivoModified(boolean activoModified)
	{
		this.activoModified = activoModified;
	}

	/** 
	 * Gets the value of activoModified
	 */
	public boolean isActivoModified()
	{
		return activoModified;
	}

	/**
	 * Method 'getUsusarioIdususario'
	 * 
	 * @return String
	 */
	public String getUsusarioIdususario()
	{
		return ususarioIdususario;
	}

	/**
	 * Method 'setUsusarioIdususario'
	 * 
	 * @param ususarioIdususario
	 */
	public void setUsusarioIdususario(String ususarioIdususario)
	{
		this.ususarioIdususario = ususarioIdususario;
		this.ususarioIdususarioModified = true;
	}

	/** 
	 * Sets the value of ususarioIdususarioModified
	 */
	public void setUsusarioIdususarioModified(boolean ususarioIdususarioModified)
	{
		this.ususarioIdususarioModified = ususarioIdususarioModified;
	}

	/** 
	 * Gets the value of ususarioIdususarioModified
	 */
	public boolean isUsusarioIdususarioModified()
	{
		return ususarioIdususarioModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Cuenta)) {
			return false;
		}
		
		final Cuenta _cast = (Cuenta) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (tipoDocumentoModified != _cast.tipoDocumentoModified) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (numeroDocumentoModified != _cast.numeroDocumentoModified) {
			return false;
		}
		
		if (primerNombre == null ? _cast.primerNombre != primerNombre : !primerNombre.equals( _cast.primerNombre )) {
			return false;
		}
		
		if (primerNombreModified != _cast.primerNombreModified) {
			return false;
		}
		
		if (segundoNombre == null ? _cast.segundoNombre != segundoNombre : !segundoNombre.equals( _cast.segundoNombre )) {
			return false;
		}
		
		if (segundoNombreModified != _cast.segundoNombreModified) {
			return false;
		}
		
		if (primerApellido == null ? _cast.primerApellido != primerApellido : !primerApellido.equals( _cast.primerApellido )) {
			return false;
		}
		
		if (primerApellidoModified != _cast.primerApellidoModified) {
			return false;
		}
		
		if (segundoApellido == null ? _cast.segundoApellido != segundoApellido : !segundoApellido.equals( _cast.segundoApellido )) {
			return false;
		}
		
		if (segundoApellidoModified != _cast.segundoApellidoModified) {
			return false;
		}
		
		if (contrasena == null ? _cast.contrasena != contrasena : !contrasena.equals( _cast.contrasena )) {
			return false;
		}
		
		if (contrasenaModified != _cast.contrasenaModified) {
			return false;
		}
		
		if (correo == null ? _cast.correo != correo : !correo.equals( _cast.correo )) {
			return false;
		}
		
		if (correoModified != _cast.correoModified) {
			return false;
		}
		
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (direccionModified != _cast.direccionModified) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (telefonoModified != _cast.telefonoModified) {
			return false;
		}
		
		if (rool == null ? _cast.rool != rool : !rool.equals( _cast.rool )) {
			return false;
		}
		
		if (roolModified != _cast.roolModified) {
			return false;
		}
		
		if (activo != _cast.activo) {
			return false;
		}
		
		if (activoModified != _cast.activoModified) {
			return false;
		}
		
		if (ususarioIdususario == null ? _cast.ususarioIdususario != ususarioIdususario : !ususarioIdususario.equals( _cast.ususarioIdususario )) {
			return false;
		}
		
		if (ususarioIdususarioModified != _cast.ususarioIdususarioModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoDocumentoModified ? 1 : 0);
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numeroDocumentoModified ? 1 : 0);
		if (primerNombre != null) {
			_hashCode = 29 * _hashCode + primerNombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (primerNombreModified ? 1 : 0);
		if (segundoNombre != null) {
			_hashCode = 29 * _hashCode + segundoNombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (segundoNombreModified ? 1 : 0);
		if (primerApellido != null) {
			_hashCode = 29 * _hashCode + primerApellido.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (primerApellidoModified ? 1 : 0);
		if (segundoApellido != null) {
			_hashCode = 29 * _hashCode + segundoApellido.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (segundoApellidoModified ? 1 : 0);
		if (contrasena != null) {
			_hashCode = 29 * _hashCode + contrasena.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contrasenaModified ? 1 : 0);
		if (correo != null) {
			_hashCode = 29 * _hashCode + correo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (correoModified ? 1 : 0);
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (direccionModified ? 1 : 0);
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (telefonoModified ? 1 : 0);
		if (rool != null) {
			_hashCode = 29 * _hashCode + rool.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (roolModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) activo;
		_hashCode = 29 * _hashCode + (activoModified ? 1 : 0);
		if (ususarioIdususario != null) {
			_hashCode = 29 * _hashCode + ususarioIdususario.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (ususarioIdususarioModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CuentaPk
	 */
	public CuentaPk createPk()
	{
		return new CuentaPk(tipoDocumento, numeroDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Cuenta: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", primerNombre=" + primerNombre );
		ret.append( ", segundoNombre=" + segundoNombre );
		ret.append( ", primerApellido=" + primerApellido );
		ret.append( ", segundoApellido=" + segundoApellido );
		ret.append( ", contrasena=" + contrasena );
		ret.append( ", correo=" + correo );
		ret.append( ", direccion=" + direccion );
		ret.append( ", telefono=" + telefono );
		ret.append( ", rool=" + rool );
		ret.append( ", activo=" + activo );
		ret.append( ", ususarioIdususario=" + ususarioIdususario );
		return ret.toString();
	}

}
