/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Factura implements Serializable
{
	/** 
	 * This attribute maps to the column ID_Factura in the factura table.
	 */
	protected int idFactura;

	/** 
	 * This attribute represents whether the attribute idFactura has been modified since being read from the database.
	 */
	protected boolean idFacturaModified = false;

	/** 
	 * This attribute maps to the column Fecha in the factura table.
	 */
	protected Date fecha;

	/** 
	 * This attribute represents whether the attribute fecha has been modified since being read from the database.
	 */
	protected boolean fechaModified = false;

	/** 
	 * This attribute maps to the column Cuenta_Tipo_Documento in the factura table.
	 */
	protected String cuentaTipoDocumento;

	/** 
	 * This attribute represents whether the attribute cuentaTipoDocumento has been modified since being read from the database.
	 */
	protected boolean cuentaTipoDocumentoModified = false;

	/** 
	 * This attribute maps to the column Cuenta_Numero_Documento in the factura table.
	 */
	protected String cuentaNumeroDocumento;

	/** 
	 * This attribute represents whether the attribute cuentaNumeroDocumento has been modified since being read from the database.
	 */
	protected boolean cuentaNumeroDocumentoModified = false;

	/**
	 * Method 'Factura'
	 * 
	 */
	public Factura()
	{
	}

	/**
	 * Method 'getIdFactura'
	 * 
	 * @return int
	 */
	public int getIdFactura()
	{
		return idFactura;
	}

	/**
	 * Method 'setIdFactura'
	 * 
	 * @param idFactura
	 */
	public void setIdFactura(int idFactura)
	{
		this.idFactura = idFactura;
		this.idFacturaModified = true;
	}

	/** 
	 * Sets the value of idFacturaModified
	 */
	public void setIdFacturaModified(boolean idFacturaModified)
	{
		this.idFacturaModified = idFacturaModified;
	}

	/** 
	 * Gets the value of idFacturaModified
	 */
	public boolean isIdFacturaModified()
	{
		return idFacturaModified;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
		this.fechaModified = true;
	}

	/** 
	 * Sets the value of fechaModified
	 */
	public void setFechaModified(boolean fechaModified)
	{
		this.fechaModified = fechaModified;
	}

	/** 
	 * Gets the value of fechaModified
	 */
	public boolean isFechaModified()
	{
		return fechaModified;
	}

	/**
	 * Method 'getCuentaTipoDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipoDocumento()
	{
		return cuentaTipoDocumento;
	}

	/**
	 * Method 'setCuentaTipoDocumento'
	 * 
	 * @param cuentaTipoDocumento
	 */
	public void setCuentaTipoDocumento(String cuentaTipoDocumento)
	{
		this.cuentaTipoDocumento = cuentaTipoDocumento;
		this.cuentaTipoDocumentoModified = true;
	}

	/** 
	 * Sets the value of cuentaTipoDocumentoModified
	 */
	public void setCuentaTipoDocumentoModified(boolean cuentaTipoDocumentoModified)
	{
		this.cuentaTipoDocumentoModified = cuentaTipoDocumentoModified;
	}

	/** 
	 * Gets the value of cuentaTipoDocumentoModified
	 */
	public boolean isCuentaTipoDocumentoModified()
	{
		return cuentaTipoDocumentoModified;
	}

	/**
	 * Method 'getCuentaNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumeroDocumento()
	{
		return cuentaNumeroDocumento;
	}

	/**
	 * Method 'setCuentaNumeroDocumento'
	 * 
	 * @param cuentaNumeroDocumento
	 */
	public void setCuentaNumeroDocumento(String cuentaNumeroDocumento)
	{
		this.cuentaNumeroDocumento = cuentaNumeroDocumento;
		this.cuentaNumeroDocumentoModified = true;
	}

	/** 
	 * Sets the value of cuentaNumeroDocumentoModified
	 */
	public void setCuentaNumeroDocumentoModified(boolean cuentaNumeroDocumentoModified)
	{
		this.cuentaNumeroDocumentoModified = cuentaNumeroDocumentoModified;
	}

	/** 
	 * Gets the value of cuentaNumeroDocumentoModified
	 */
	public boolean isCuentaNumeroDocumentoModified()
	{
		return cuentaNumeroDocumentoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Factura)) {
			return false;
		}
		
		final Factura _cast = (Factura) _other;
		if (idFactura != _cast.idFactura) {
			return false;
		}
		
		if (idFacturaModified != _cast.idFacturaModified) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (fechaModified != _cast.fechaModified) {
			return false;
		}
		
		if (cuentaTipoDocumento == null ? _cast.cuentaTipoDocumento != cuentaTipoDocumento : !cuentaTipoDocumento.equals( _cast.cuentaTipoDocumento )) {
			return false;
		}
		
		if (cuentaTipoDocumentoModified != _cast.cuentaTipoDocumentoModified) {
			return false;
		}
		
		if (cuentaNumeroDocumento == null ? _cast.cuentaNumeroDocumento != cuentaNumeroDocumento : !cuentaNumeroDocumento.equals( _cast.cuentaNumeroDocumento )) {
			return false;
		}
		
		if (cuentaNumeroDocumentoModified != _cast.cuentaNumeroDocumentoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idFactura;
		_hashCode = 29 * _hashCode + (idFacturaModified ? 1 : 0);
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaModified ? 1 : 0);
		if (cuentaTipoDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipoDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (cuentaTipoDocumentoModified ? 1 : 0);
		if (cuentaNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumeroDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (cuentaNumeroDocumentoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FacturaPk
	 */
	public FacturaPk createPk()
	{
		return new FacturaPk(idFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Factura: " );
		ret.append( "idFactura=" + idFactura );
		ret.append( ", fecha=" + fecha );
		ret.append( ", cuentaTipoDocumento=" + cuentaTipoDocumento );
		ret.append( ", cuentaNumeroDocumento=" + cuentaNumeroDocumento );
		return ret.toString();
	}

}
