/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Pago implements Serializable
{
	/** 
	 * This attribute maps to the column Factura_ID_Factura in the pago table.
	 */
	protected int facturaIdFactura;

	/** 
	 * This attribute represents whether the attribute facturaIdFactura has been modified since being read from the database.
	 */
	protected boolean facturaIdFacturaModified = false;

	/** 
	 * This attribute maps to the column Tipo_Pago in the pago table.
	 */
	protected String tipoPago;

	/** 
	 * This attribute represents whether the attribute tipoPago has been modified since being read from the database.
	 */
	protected boolean tipoPagoModified = false;

	/** 
	 * This attribute maps to the column Numero_Tarjeta in the pago table.
	 */
	protected String numeroTarjeta;

	/** 
	 * This attribute represents whether the attribute numeroTarjeta has been modified since being read from the database.
	 */
	protected boolean numeroTarjetaModified = false;

	/**
	 * Method 'Pago'
	 * 
	 */
	public Pago()
	{
	}

	/**
	 * Method 'getFacturaIdFactura'
	 * 
	 * @return int
	 */
	public int getFacturaIdFactura()
	{
		return facturaIdFactura;
	}

	/**
	 * Method 'setFacturaIdFactura'
	 * 
	 * @param facturaIdFactura
	 */
	public void setFacturaIdFactura(int facturaIdFactura)
	{
		this.facturaIdFactura = facturaIdFactura;
		this.facturaIdFacturaModified = true;
	}

	/** 
	 * Sets the value of facturaIdFacturaModified
	 */
	public void setFacturaIdFacturaModified(boolean facturaIdFacturaModified)
	{
		this.facturaIdFacturaModified = facturaIdFacturaModified;
	}

	/** 
	 * Gets the value of facturaIdFacturaModified
	 */
	public boolean isFacturaIdFacturaModified()
	{
		return facturaIdFacturaModified;
	}

	/**
	 * Method 'getTipoPago'
	 * 
	 * @return String
	 */
	public String getTipoPago()
	{
		return tipoPago;
	}

	/**
	 * Method 'setTipoPago'
	 * 
	 * @param tipoPago
	 */
	public void setTipoPago(String tipoPago)
	{
		this.tipoPago = tipoPago;
		this.tipoPagoModified = true;
	}

	/** 
	 * Sets the value of tipoPagoModified
	 */
	public void setTipoPagoModified(boolean tipoPagoModified)
	{
		this.tipoPagoModified = tipoPagoModified;
	}

	/** 
	 * Gets the value of tipoPagoModified
	 */
	public boolean isTipoPagoModified()
	{
		return tipoPagoModified;
	}

	/**
	 * Method 'getNumeroTarjeta'
	 * 
	 * @return String
	 */
	public String getNumeroTarjeta()
	{
		return numeroTarjeta;
	}

	/**
	 * Method 'setNumeroTarjeta'
	 * 
	 * @param numeroTarjeta
	 */
	public void setNumeroTarjeta(String numeroTarjeta)
	{
		this.numeroTarjeta = numeroTarjeta;
		this.numeroTarjetaModified = true;
	}

	/** 
	 * Sets the value of numeroTarjetaModified
	 */
	public void setNumeroTarjetaModified(boolean numeroTarjetaModified)
	{
		this.numeroTarjetaModified = numeroTarjetaModified;
	}

	/** 
	 * Gets the value of numeroTarjetaModified
	 */
	public boolean isNumeroTarjetaModified()
	{
		return numeroTarjetaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pago)) {
			return false;
		}
		
		final Pago _cast = (Pago) _other;
		if (facturaIdFactura != _cast.facturaIdFactura) {
			return false;
		}
		
		if (facturaIdFacturaModified != _cast.facturaIdFacturaModified) {
			return false;
		}
		
		if (tipoPago == null ? _cast.tipoPago != tipoPago : !tipoPago.equals( _cast.tipoPago )) {
			return false;
		}
		
		if (tipoPagoModified != _cast.tipoPagoModified) {
			return false;
		}
		
		if (numeroTarjeta == null ? _cast.numeroTarjeta != numeroTarjeta : !numeroTarjeta.equals( _cast.numeroTarjeta )) {
			return false;
		}
		
		if (numeroTarjetaModified != _cast.numeroTarjetaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + facturaIdFactura;
		_hashCode = 29 * _hashCode + (facturaIdFacturaModified ? 1 : 0);
		if (tipoPago != null) {
			_hashCode = 29 * _hashCode + tipoPago.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoPagoModified ? 1 : 0);
		if (numeroTarjeta != null) {
			_hashCode = 29 * _hashCode + numeroTarjeta.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numeroTarjetaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PagoPk
	 */
	public PagoPk createPk()
	{
		return new PagoPk(facturaIdFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Pago: " );
		ret.append( "facturaIdFactura=" + facturaIdFactura );
		ret.append( ", tipoPago=" + tipoPago );
		ret.append( ", numeroTarjeta=" + numeroTarjeta );
		return ret.toString();
	}

}
