/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.negocio.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.akuavida.integracion.dao.MunicipioDao;
import edu.co.sena.akuavida.integracion.dto.Municipio;
import edu.co.sena.akuavida.integracion.exceptions.MunicipioDaoException;
import edu.co.sena.akuavida.integracion.factory.MunicipioDaoFactory;

public class MunicipioDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		findAll();
		// findByDepartamento("");
		// findWhereIdMunicipioEquals("");
		// findWhereNombreMunicipioEquals("");
		// findWhereDepartamentoIddepartamentoEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			MunicipioDao _dao = getMunicipioDao();
			Municipio _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByDepartamento'
	 * 
	 * @param departamentoIddepartamento
	 */
	public static void findByDepartamento(String departamentoIddepartamento)
	{
		try {
			MunicipioDao _dao = getMunicipioDao();
			Municipio _result[] = _dao.findByDepartamento(departamentoIddepartamento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdMunicipioEquals'
	 * 
	 * @param idMunicipio
	 */
	public static void findWhereIdMunicipioEquals(String idMunicipio)
	{
		try {
			MunicipioDao _dao = getMunicipioDao();
			Municipio _result[] = _dao.findWhereIdMunicipioEquals(idMunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreMunicipioEquals'
	 * 
	 * @param nombreMunicipio
	 */
	public static void findWhereNombreMunicipioEquals(String nombreMunicipio)
	{
		try {
			MunicipioDao _dao = getMunicipioDao();
			Municipio _result[] = _dao.findWhereNombreMunicipioEquals(nombreMunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDepartamentoIddepartamentoEquals'
	 * 
	 * @param departamentoIddepartamento
	 */
	public static void findWhereDepartamentoIddepartamentoEquals(String departamentoIddepartamento)
	{
		try {
			MunicipioDao _dao = getMunicipioDao();
			Municipio _result[] = _dao.findWhereDepartamentoIddepartamentoEquals(departamentoIddepartamento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getMunicipioDao'
	 * 
	 * @return MunicipioDao
	 */
	public static MunicipioDao getMunicipioDao()
	{
		return MunicipioDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Municipio dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdMunicipio() );
		buf.append( ", " );
		buf.append( dto.getNombreMunicipio() );
		buf.append( ", " );
		buf.append( dto.getDepartamentoIddepartamento() );
		System.out.println( buf.toString() );
	}

}
