/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.jdbc;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.dto.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CategoriasDaoImpl extends AbstractDAO implements CategoriasDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_Categoria, Nombre, Activa, Pariente FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_Categoria, Nombre, Activa, Pariente ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_Categoria = ?, Nombre = ?, Activa = ?, Pariente = ? WHERE ID_Categoria = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_Categoria = ?";

	/** 
	 * Index of column ID_Categoria
	 */
	protected static final int COLUMN_ID_CATEGORIA = 1;

	/** 
	 * Index of column Nombre
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Index of column Activa
	 */
	protected static final int COLUMN_ACTIVA = 3;

	/** 
	 * Index of column Pariente
	 */
	protected static final int COLUMN_PARIENTE = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ID_Categoria
	 */
	protected static final int PK_COLUMN_ID_CATEGORIA = 1;

	/** 
	 * Inserts a new row in the categorias table.
	 */
	public CategoriasPk insert(Categorias dto) throws CategoriasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdCategoria() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setShort( index++, dto.getActiva() );
			stmt.setInt( index++, dto.getPariente() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdCategoria( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CategoriasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the categorias table.
	 */
	public void update(CategoriasPk pk, Categorias dto) throws CategoriasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdCategoria() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setShort( index++, dto.getActiva() );
			stmt.setInt( index++, dto.getPariente() );
			stmt.setInt( 5, pk.getIdCategoria() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CategoriasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the categorias table.
	 */
	public void delete(CategoriasPk pk) throws CategoriasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdCategoria() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CategoriasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the categorias table that matches the specified primary-key value.
	 */
	public Categorias findByPrimaryKey(CategoriasPk pk) throws CategoriasDaoException
	{
		return findByPrimaryKey( pk.getIdCategoria() );
	}

	/** 
	 * Returns all rows from the categorias table that match the criteria 'ID_Categoria = :idCategoria'.
	 */
	public Categorias findByPrimaryKey(int idCategoria) throws CategoriasDaoException
	{
		Categorias ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_Categoria = ?", new Object[] {  new Integer(idCategoria) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the categorias table that match the criteria ''.
	 */
	public Categorias[] findAll() throws CategoriasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_Categoria", null );
	}

	/** 
	 * Returns all rows from the categorias table that match the criteria 'ID_Categoria = :idCategoria'.
	 */
	public Categorias[] findWhereIdCategoriaEquals(int idCategoria) throws CategoriasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_Categoria = ? ORDER BY ID_Categoria", new Object[] {  new Integer(idCategoria) } );
	}

	/** 
	 * Returns all rows from the categorias table that match the criteria 'Nombre = :nombre'.
	 */
	public Categorias[] findWhereNombreEquals(String nombre) throws CategoriasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Nombre = ? ORDER BY Nombre", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the categorias table that match the criteria 'Activa = :activa'.
	 */
	public Categorias[] findWhereActivaEquals(short activa) throws CategoriasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Activa = ? ORDER BY Activa", new Object[] {  new Short(activa) } );
	}

	/** 
	 * Returns all rows from the categorias table that match the criteria 'Pariente = :pariente'.
	 */
	public Categorias[] findWhereParienteEquals(int pariente) throws CategoriasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Pariente = ? ORDER BY Pariente", new Object[] {  new Integer(pariente) } );
	}

	/**
	 * Method 'CategoriasDaoImpl'
	 * 
	 */
	public CategoriasDaoImpl()
	{
	}

	/**
	 * Method 'CategoriasDaoImpl'
	 * 
	 * @param userConn
	 */
	public CategoriasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "akuavida.categorias";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Categorias fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Categorias dto = new Categorias();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Categorias[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Categorias dto = new Categorias();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Categorias ret[] = new Categorias[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Categorias dto, ResultSet rs) throws SQLException
	{
		dto.setIdCategoria( rs.getInt( COLUMN_ID_CATEGORIA ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setActiva( rs.getShort( COLUMN_ACTIVA ) );
		dto.setPariente( rs.getInt( COLUMN_PARIENTE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Categorias dto)
	{
	}

	/** 
	 * Returns all rows from the categorias table that match the specified arbitrary SQL statement
	 */
	public Categorias[] findByDynamicSelect(String sql, Object[] sqlParams) throws CategoriasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CategoriasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the categorias table that match the specified arbitrary SQL statement
	 */
	public Categorias[] findByDynamicWhere(String sql, Object[] sqlParams) throws CategoriasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CategoriasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
