/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Producto implements Serializable
{
	/** 
	 * This attribute maps to the column ID_producto in the producto table.
	 */
	protected String idProducto;

	/** 
	 * This attribute represents whether the attribute idProducto has been modified since being read from the database.
	 */
	protected boolean idProductoModified = false;

	/** 
	 * This attribute maps to the column Nombre in the producto table.
	 */
	protected String nombre;

	/** 
	 * This attribute represents whether the attribute nombre has been modified since being read from the database.
	 */
	protected boolean nombreModified = false;

	/** 
	 * This attribute maps to the column Precio in the producto table.
	 */
	protected float precio;

	/** 
	 * This attribute represents whether the attribute precio has been modified since being read from the database.
	 */
	protected boolean precioModified = false;

	/** 
	 * This attribute maps to the column Imagen in the producto table.
	 */
	protected byte[] imagen;

	/** 
	 * This attribute represents whether the attribute imagen has been modified since being read from the database.
	 */
	protected boolean imagenModified = false;

	/** 
	 * This attribute maps to the column Descripcion in the producto table.
	 */
	protected String descripcion;

	/** 
	 * This attribute represents whether the attribute descripcion has been modified since being read from the database.
	 */
	protected boolean descripcionModified = false;

	/** 
	 * This attribute maps to the column Cantidad in the producto table.
	 */
	protected int cantidad;

	/** 
	 * This attribute represents whether the attribute cantidad has been modified since being read from the database.
	 */
	protected boolean cantidadModified = false;

	/** 
	 * This attribute maps to the column Activo in the producto table.
	 */
	protected short activo;

	/** 
	 * This attribute represents whether the attribute activo has been modified since being read from the database.
	 */
	protected boolean activoModified = false;

	/** 
	 * This attribute maps to the column impuesto in the producto table.
	 */
	protected float impuesto;

	/** 
	 * This attribute represents whether the attribute impuesto has been modified since being read from the database.
	 */
	protected boolean impuestoModified = false;

	/** 
	 * This attribute maps to the column Categorias_ID_Categoria in the producto table.
	 */
	protected int categoriasIdCategoria;

	/** 
	 * This attribute represents whether the attribute categoriasIdCategoria has been modified since being read from the database.
	 */
	protected boolean categoriasIdCategoriaModified = false;

	/**
	 * Method 'Producto'
	 * 
	 */
	public Producto()
	{
	}

	/**
	 * Method 'getIdProducto'
	 * 
	 * @return String
	 */
	public String getIdProducto()
	{
		return idProducto;
	}

	/**
	 * Method 'setIdProducto'
	 * 
	 * @param idProducto
	 */
	public void setIdProducto(String idProducto)
	{
		this.idProducto = idProducto;
		this.idProductoModified = true;
	}

	/** 
	 * Sets the value of idProductoModified
	 */
	public void setIdProductoModified(boolean idProductoModified)
	{
		this.idProductoModified = idProductoModified;
	}

	/** 
	 * Gets the value of idProductoModified
	 */
	public boolean isIdProductoModified()
	{
		return idProductoModified;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
		this.nombreModified = true;
	}

	/** 
	 * Sets the value of nombreModified
	 */
	public void setNombreModified(boolean nombreModified)
	{
		this.nombreModified = nombreModified;
	}

	/** 
	 * Gets the value of nombreModified
	 */
	public boolean isNombreModified()
	{
		return nombreModified;
	}

	/**
	 * Method 'getPrecio'
	 * 
	 * @return float
	 */
	public float getPrecio()
	{
		return precio;
	}

	/**
	 * Method 'setPrecio'
	 * 
	 * @param precio
	 */
	public void setPrecio(float precio)
	{
		this.precio = precio;
		this.precioModified = true;
	}

	/** 
	 * Sets the value of precioModified
	 */
	public void setPrecioModified(boolean precioModified)
	{
		this.precioModified = precioModified;
	}

	/** 
	 * Gets the value of precioModified
	 */
	public boolean isPrecioModified()
	{
		return precioModified;
	}

	/**
	 * Method 'getImagen'
	 * 
	 * @return byte[]
	 */
	public byte[] getImagen()
	{
		return imagen;
	}

	/**
	 * Method 'setImagen'
	 * 
	 * @param imagen
	 */
	public void setImagen(byte[] imagen)
	{
		this.imagen = imagen;
		this.imagenModified = true;
	}

	/** 
	 * Sets the value of imagenModified
	 */
	public void setImagenModified(boolean imagenModified)
	{
		this.imagenModified = imagenModified;
	}

	/** 
	 * Gets the value of imagenModified
	 */
	public boolean isImagenModified()
	{
		return imagenModified;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
		this.descripcionModified = true;
	}

	/** 
	 * Sets the value of descripcionModified
	 */
	public void setDescripcionModified(boolean descripcionModified)
	{
		this.descripcionModified = descripcionModified;
	}

	/** 
	 * Gets the value of descripcionModified
	 */
	public boolean isDescripcionModified()
	{
		return descripcionModified;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadModified = true;
	}

	/** 
	 * Sets the value of cantidadModified
	 */
	public void setCantidadModified(boolean cantidadModified)
	{
		this.cantidadModified = cantidadModified;
	}

	/** 
	 * Gets the value of cantidadModified
	 */
	public boolean isCantidadModified()
	{
		return cantidadModified;
	}

	/**
	 * Method 'getActivo'
	 * 
	 * @return short
	 */
	public short getActivo()
	{
		return activo;
	}

	/**
	 * Method 'setActivo'
	 * 
	 * @param activo
	 */
	public void setActivo(short activo)
	{
		this.activo = activo;
		this.activoModified = true;
	}

	/** 
	 * Sets the value of activoModified
	 */
	public void setActivoModified(boolean activoModified)
	{
		this.activoModified = activoModified;
	}

	/** 
	 * Gets the value of activoModified
	 */
	public boolean isActivoModified()
	{
		return activoModified;
	}

	/**
	 * Method 'getImpuesto'
	 * 
	 * @return float
	 */
	public float getImpuesto()
	{
		return impuesto;
	}

	/**
	 * Method 'setImpuesto'
	 * 
	 * @param impuesto
	 */
	public void setImpuesto(float impuesto)
	{
		this.impuesto = impuesto;
		this.impuestoModified = true;
	}

	/** 
	 * Sets the value of impuestoModified
	 */
	public void setImpuestoModified(boolean impuestoModified)
	{
		this.impuestoModified = impuestoModified;
	}

	/** 
	 * Gets the value of impuestoModified
	 */
	public boolean isImpuestoModified()
	{
		return impuestoModified;
	}

	/**
	 * Method 'getCategoriasIdCategoria'
	 * 
	 * @return int
	 */
	public int getCategoriasIdCategoria()
	{
		return categoriasIdCategoria;
	}

	/**
	 * Method 'setCategoriasIdCategoria'
	 * 
	 * @param categoriasIdCategoria
	 */
	public void setCategoriasIdCategoria(int categoriasIdCategoria)
	{
		this.categoriasIdCategoria = categoriasIdCategoria;
		this.categoriasIdCategoriaModified = true;
	}

	/** 
	 * Sets the value of categoriasIdCategoriaModified
	 */
	public void setCategoriasIdCategoriaModified(boolean categoriasIdCategoriaModified)
	{
		this.categoriasIdCategoriaModified = categoriasIdCategoriaModified;
	}

	/** 
	 * Gets the value of categoriasIdCategoriaModified
	 */
	public boolean isCategoriasIdCategoriaModified()
	{
		return categoriasIdCategoriaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Producto)) {
			return false;
		}
		
		final Producto _cast = (Producto) _other;
		if (idProducto == null ? _cast.idProducto != idProducto : !idProducto.equals( _cast.idProducto )) {
			return false;
		}
		
		if (idProductoModified != _cast.idProductoModified) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (nombreModified != _cast.nombreModified) {
			return false;
		}
		
		if (precio != _cast.precio) {
			return false;
		}
		
		if (precioModified != _cast.precioModified) {
			return false;
		}
		
		if (imagen == null ? _cast.imagen != imagen : !imagen.equals( _cast.imagen )) {
			return false;
		}
		
		if (imagenModified != _cast.imagenModified) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		if (descripcionModified != _cast.descripcionModified) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadModified != _cast.cantidadModified) {
			return false;
		}
		
		if (activo != _cast.activo) {
			return false;
		}
		
		if (activoModified != _cast.activoModified) {
			return false;
		}
		
		if (impuesto != _cast.impuesto) {
			return false;
		}
		
		if (impuestoModified != _cast.impuestoModified) {
			return false;
		}
		
		if (categoriasIdCategoria != _cast.categoriasIdCategoria) {
			return false;
		}
		
		if (categoriasIdCategoriaModified != _cast.categoriasIdCategoriaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idProducto != null) {
			_hashCode = 29 * _hashCode + idProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idProductoModified ? 1 : 0);
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(precio);
		_hashCode = 29 * _hashCode + (precioModified ? 1 : 0);
		if (imagen != null) {
			_hashCode = 29 * _hashCode + imagen.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (imagenModified ? 1 : 0);
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (descripcionModified ? 1 : 0);
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + (cantidadModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) activo;
		_hashCode = 29 * _hashCode + (activoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(impuesto);
		_hashCode = 29 * _hashCode + (impuestoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + categoriasIdCategoria;
		_hashCode = 29 * _hashCode + (categoriasIdCategoriaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProductoPk
	 */
	public ProductoPk createPk()
	{
		return new ProductoPk(idProducto);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Producto: " );
		ret.append( "idProducto=" + idProducto );
		ret.append( ", nombre=" + nombre );
		ret.append( ", precio=" + precio );
		ret.append( ", imagen=" + imagen );
		ret.append( ", descripcion=" + descripcion );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", activo=" + activo );
		ret.append( ", impuesto=" + impuesto );
		ret.append( ", categoriasIdCategoria=" + categoriasIdCategoria );
		return ret.toString();
	}

}
