/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the promociones table.
 */
public class PromocionesPk implements Serializable
{
	protected String idPromocion;

	/** 
	 * Sets the value of idPromocion
	 */
	public void setIdPromocion(String idPromocion)
	{
		this.idPromocion = idPromocion;
	}

	/** 
	 * Gets the value of idPromocion
	 */
	public String getIdPromocion()
	{
		return idPromocion;
	}

	/**
	 * Method 'PromocionesPk'
	 * 
	 */
	public PromocionesPk()
	{
	}

	/**
	 * Method 'PromocionesPk'
	 * 
	 * @param idPromocion
	 */
	public PromocionesPk(final String idPromocion)
	{
		this.idPromocion = idPromocion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PromocionesPk)) {
			return false;
		}
		
		final PromocionesPk _cast = (PromocionesPk) _other;
		if (idPromocion == null ? _cast.idPromocion != idPromocion : !idPromocion.equals( _cast.idPromocion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idPromocion != null) {
			_hashCode = 29 * _hashCode + idPromocion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.PromocionesPk: " );
		ret.append( "idPromocion=" + idPromocion );
		return ret.toString();
	}

}
