/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dto;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Ususario implements Serializable
{
	/** 
	 * This attribute maps to the column idUsusario in the ususario table.
	 */
	protected String idUsusario;

	/** 
	 * This attribute represents whether the attribute idUsusario has been modified since being read from the database.
	 */
	protected boolean idUsusarioModified = false;

	/** 
	 * This attribute maps to the column password in the ususario table.
	 */
	protected String password;

	/** 
	 * This attribute represents whether the attribute password has been modified since being read from the database.
	 */
	protected boolean passwordModified = false;

	/** 
	 * This attribute maps to the column rol in the ususario table.
	 */
	protected String rol;

	/** 
	 * This attribute represents whether the attribute rol has been modified since being read from the database.
	 */
	protected boolean rolModified = false;

	/** 
	 * This attribute maps to the column estado in the ususario table.
	 */
	protected String estado;

	/** 
	 * This attribute represents whether the attribute estado has been modified since being read from the database.
	 */
	protected boolean estadoModified = false;

	/**
	 * Method 'Ususario'
	 * 
	 */
	public Ususario()
	{
	}

	/**
	 * Method 'getIdUsusario'
	 * 
	 * @return String
	 */
	public String getIdUsusario()
	{
		return idUsusario;
	}

	/**
	 * Method 'setIdUsusario'
	 * 
	 * @param idUsusario
	 */
	public void setIdUsusario(String idUsusario)
	{
		this.idUsusario = idUsusario;
		this.idUsusarioModified = true;
	}

	/** 
	 * Sets the value of idUsusarioModified
	 */
	public void setIdUsusarioModified(boolean idUsusarioModified)
	{
		this.idUsusarioModified = idUsusarioModified;
	}

	/** 
	 * Gets the value of idUsusarioModified
	 */
	public boolean isIdUsusarioModified()
	{
		return idUsusarioModified;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
		this.passwordModified = true;
	}

	/** 
	 * Sets the value of passwordModified
	 */
	public void setPasswordModified(boolean passwordModified)
	{
		this.passwordModified = passwordModified;
	}

	/** 
	 * Gets the value of passwordModified
	 */
	public boolean isPasswordModified()
	{
		return passwordModified;
	}

	/**
	 * Method 'getRol'
	 * 
	 * @return String
	 */
	public String getRol()
	{
		return rol;
	}

	/**
	 * Method 'setRol'
	 * 
	 * @param rol
	 */
	public void setRol(String rol)
	{
		this.rol = rol;
		this.rolModified = true;
	}

	/** 
	 * Sets the value of rolModified
	 */
	public void setRolModified(boolean rolModified)
	{
		this.rolModified = rolModified;
	}

	/** 
	 * Gets the value of rolModified
	 */
	public boolean isRolModified()
	{
		return rolModified;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return String
	 */
	public String getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(String estado)
	{
		this.estado = estado;
		this.estadoModified = true;
	}

	/** 
	 * Sets the value of estadoModified
	 */
	public void setEstadoModified(boolean estadoModified)
	{
		this.estadoModified = estadoModified;
	}

	/** 
	 * Gets the value of estadoModified
	 */
	public boolean isEstadoModified()
	{
		return estadoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Ususario)) {
			return false;
		}
		
		final Ususario _cast = (Ususario) _other;
		if (idUsusario == null ? _cast.idUsusario != idUsusario : !idUsusario.equals( _cast.idUsusario )) {
			return false;
		}
		
		if (idUsusarioModified != _cast.idUsusarioModified) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (passwordModified != _cast.passwordModified) {
			return false;
		}
		
		if (rol == null ? _cast.rol != rol : !rol.equals( _cast.rol )) {
			return false;
		}
		
		if (rolModified != _cast.rolModified) {
			return false;
		}
		
		if (estado == null ? _cast.estado != estado : !estado.equals( _cast.estado )) {
			return false;
		}
		
		if (estadoModified != _cast.estadoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idUsusario != null) {
			_hashCode = 29 * _hashCode + idUsusario.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idUsusarioModified ? 1 : 0);
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (passwordModified ? 1 : 0);
		if (rol != null) {
			_hashCode = 29 * _hashCode + rol.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rolModified ? 1 : 0);
		if (estado != null) {
			_hashCode = 29 * _hashCode + estado.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (estadoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UsusarioPk
	 */
	public UsusarioPk createPk()
	{
		return new UsusarioPk(idUsusario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.akuavida.integracion.dto.Ususario: " );
		ret.append( "idUsusario=" + idUsusario );
		ret.append( ", password=" + password );
		ret.append( ", rol=" + rol );
		ret.append( ", estado=" + estado );
		return ret.toString();
	}

}
