/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.dao;

import edu.co.sena.akuavida.integracion.dto.*;
import edu.co.sena.akuavida.integracion.exceptions.*;

public interface CuentaDao
{
	/** 
	 * Inserts a new row in the cuenta table.
	 */
	public CuentaPk insert(Cuenta dto) throws CuentaDaoException;

	/** 
	 * Updates a single row in the cuenta table.
	 */
	public void update(CuentaPk pk, Cuenta dto) throws CuentaDaoException;

	/** 
	 * Deletes a single row in the cuenta table.
	 */
	public void delete(CuentaPk pk) throws CuentaDaoException;

	/** 
	 * Returns the rows from the cuenta table that matches the specified primary-key value.
	 */
	public Cuenta findByPrimaryKey(CuentaPk pk) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Tipo_Documento = :tipoDocumento AND Numero_Documento = :numeroDocumento'.
	 */
	public Cuenta findByPrimaryKey(String tipoDocumento, String numeroDocumento) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria ''.
	 */
	public Cuenta[] findAll() throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Ususario_idUsusario = :ususarioIdususario'.
	 */
	public Cuenta[] findByUsusario(String ususarioIdususario) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Tipo_Documento = :tipoDocumento'.
	 */
	public Cuenta[] findWhereTipoDocumentoEquals(String tipoDocumento) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Numero_Documento = :numeroDocumento'.
	 */
	public Cuenta[] findWhereNumeroDocumentoEquals(String numeroDocumento) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Primer_Nombre = :primerNombre'.
	 */
	public Cuenta[] findWherePrimerNombreEquals(String primerNombre) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Segundo_Nombre = :segundoNombre'.
	 */
	public Cuenta[] findWhereSegundoNombreEquals(String segundoNombre) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Primer_Apellido = :primerApellido'.
	 */
	public Cuenta[] findWherePrimerApellidoEquals(String primerApellido) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Segundo_Apellido = :segundoApellido'.
	 */
	public Cuenta[] findWhereSegundoApellidoEquals(String segundoApellido) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Contrasena = :contrasena'.
	 */
	public Cuenta[] findWhereContrasenaEquals(String contrasena) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Correo = :correo'.
	 */
	public Cuenta[] findWhereCorreoEquals(String correo) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Direccion = :direccion'.
	 */
	public Cuenta[] findWhereDireccionEquals(String direccion) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Telefono = :telefono'.
	 */
	public Cuenta[] findWhereTelefonoEquals(String telefono) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Rool = :rool'.
	 */
	public Cuenta[] findWhereRoolEquals(String rool) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Activo = :activo'.
	 */
	public Cuenta[] findWhereActivoEquals(short activo) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Ususario_idUsusario = :ususarioIdususario'.
	 */
	public Cuenta[] findWhereUsusarioIdususarioEquals(String ususarioIdususario) throws CuentaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the cuenta table that match the specified arbitrary SQL statement
	 */
	public Cuenta[] findByDynamicSelect(String sql, Object[] sqlParams) throws CuentaDaoException;

	/** 
	 * Returns all rows from the cuenta table that match the specified arbitrary SQL statement
	 */
	public Cuenta[] findByDynamicWhere(String sql, Object[] sqlParams) throws CuentaDaoException;

}
