/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.integracion.jdbc;

import edu.co.sena.akuavida.integracion.dao.*;
import edu.co.sena.akuavida.integracion.factory.*;
import edu.co.sena.akuavida.integracion.dto.*;
import edu.co.sena.akuavida.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ProductoDaoImpl extends AbstractDAO implements ProductoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( ProductoDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_producto, Nombre, Precio, Imagen, Descripcion, Cantidad, Activo, impuesto, Categorias_ID_Categoria FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_producto, Nombre, Precio, Imagen, Descripcion, Cantidad, Activo, impuesto, Categorias_ID_Categoria ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_producto = ?, Nombre = ?, Precio = ?, Imagen = ?, Descripcion = ?, Cantidad = ?, Activo = ?, impuesto = ?, Categorias_ID_Categoria = ? WHERE ID_producto = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_producto = ?";

	/** 
	 * Index of column ID_producto
	 */
	protected static final int COLUMN_ID_PRODUCTO = 1;

	/** 
	 * Index of column Nombre
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Index of column Precio
	 */
	protected static final int COLUMN_PRECIO = 3;

	/** 
	 * Index of column Imagen
	 */
	protected static final int COLUMN_IMAGEN = 4;

	/** 
	 * Index of column Descripcion
	 */
	protected static final int COLUMN_DESCRIPCION = 5;

	/** 
	 * Index of column Cantidad
	 */
	protected static final int COLUMN_CANTIDAD = 6;

	/** 
	 * Index of column Activo
	 */
	protected static final int COLUMN_ACTIVO = 7;

	/** 
	 * Index of column impuesto
	 */
	protected static final int COLUMN_IMPUESTO = 8;

	/** 
	 * Index of column Categorias_ID_Categoria
	 */
	protected static final int COLUMN_CATEGORIAS_ID_CATEGORIA = 9;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 9;

	/** 
	 * Index of primary-key column ID_producto
	 */
	protected static final int PK_COLUMN_ID_PRODUCTO = 1;

	/** 
	 * Inserts a new row in the producto table.
	 */
	public ProductoPk insert(Producto dto) throws ProductoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdProductoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_producto" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Nombre" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPrecioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Precio" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isImagenModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Imagen" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDescripcionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Descripcion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCantidadModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Cantidad" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isActivoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Activo" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isImpuestoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "impuesto" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCategoriasIdCategoriaModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Categorias_ID_Categoria" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdProductoModified()) {
				stmt.setString( index++, dto.getIdProducto() );
			}
		
			if (dto.isNombreModified()) {
				stmt.setString( index++, dto.getNombre() );
			}
		
			if (dto.isPrecioModified()) {
				stmt.setFloat( index++, dto.getPrecio() );
			}
		
			if (dto.isImagenModified()) {
				super.setBlobColumn(stmt, index++, dto.getImagen() );
			}
		
			if (dto.isDescripcionModified()) {
				stmt.setString( index++, dto.getDescripcion() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isActivoModified()) {
				stmt.setShort( index++, dto.getActivo() );
			}
		
			if (dto.isImpuestoModified()) {
				stmt.setFloat( index++, dto.getImpuesto() );
			}
		
			if (dto.isCategoriasIdCategoriaModified()) {
				stmt.setInt( index++, dto.getCategoriasIdCategoria() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the producto table.
	 */
	public void update(ProductoPk pk, Producto dto) throws ProductoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdProductoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_producto=?" );
				modified=true;
			}
		
			if (dto.isNombreModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Nombre=?" );
				modified=true;
			}
		
			if (dto.isPrecioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Precio=?" );
				modified=true;
			}
		
			if (dto.isImagenModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Imagen=?" );
				modified=true;
			}
		
			if (dto.isDescripcionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Descripcion=?" );
				modified=true;
			}
		
			if (dto.isCantidadModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Cantidad=?" );
				modified=true;
			}
		
			if (dto.isActivoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Activo=?" );
				modified=true;
			}
		
			if (dto.isImpuestoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "impuesto=?" );
				modified=true;
			}
		
			if (dto.isCategoriasIdCategoriaModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Categorias_ID_Categoria=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_producto=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdProductoModified()) {
				stmt.setString( index++, dto.getIdProducto() );
			}
		
			if (dto.isNombreModified()) {
				stmt.setString( index++, dto.getNombre() );
			}
		
			if (dto.isPrecioModified()) {
				stmt.setFloat( index++, dto.getPrecio() );
			}
		
			if (dto.isImagenModified()) {
				super.setBlobColumn(stmt, index++, dto.getImagen() );
			}
		
			if (dto.isDescripcionModified()) {
				stmt.setString( index++, dto.getDescripcion() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isActivoModified()) {
				stmt.setShort( index++, dto.getActivo() );
			}
		
			if (dto.isImpuestoModified()) {
				stmt.setFloat( index++, dto.getImpuesto() );
			}
		
			if (dto.isCategoriasIdCategoriaModified()) {
				stmt.setInt( index++, dto.getCategoriasIdCategoria() );
			}
		
			stmt.setString( index++, pk.getIdProducto() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the producto table.
	 */
	public void delete(ProductoPk pk) throws ProductoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getIdProducto() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the producto table that matches the specified primary-key value.
	 */
	public Producto findByPrimaryKey(ProductoPk pk) throws ProductoDaoException
	{
		return findByPrimaryKey( pk.getIdProducto() );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'ID_producto = :idProducto'.
	 */
	public Producto findByPrimaryKey(String idProducto) throws ProductoDaoException
	{
		Producto ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_producto = ?", new Object[] { idProducto } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the producto table that match the criteria ''.
	 */
	public Producto[] findAll() throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_producto", null );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Categorias_ID_Categoria = :categoriasIdCategoria'.
	 */
	public Producto[] findByCategorias(int categoriasIdCategoria) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Categorias_ID_Categoria = ?", new Object[] {  new Integer(categoriasIdCategoria) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'ID_producto = :idProducto'.
	 */
	public Producto[] findWhereIdProductoEquals(String idProducto) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_producto = ? ORDER BY ID_producto", new Object[] { idProducto } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Nombre = :nombre'.
	 */
	public Producto[] findWhereNombreEquals(String nombre) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Nombre = ? ORDER BY Nombre", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Precio = :precio'.
	 */
	public Producto[] findWherePrecioEquals(float precio) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Precio = ? ORDER BY Precio", new Object[] {  new Float(precio) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Imagen = :imagen'.
	 */
	public Producto[] findWhereImagenEquals(byte[] imagen) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Imagen = ? ORDER BY Imagen", new Object[] { imagen } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Descripcion = :descripcion'.
	 */
	public Producto[] findWhereDescripcionEquals(String descripcion) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Descripcion = ? ORDER BY Descripcion", new Object[] { descripcion } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Cantidad = :cantidad'.
	 */
	public Producto[] findWhereCantidadEquals(int cantidad) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Cantidad = ? ORDER BY Cantidad", new Object[] {  new Integer(cantidad) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Activo = :activo'.
	 */
	public Producto[] findWhereActivoEquals(short activo) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Activo = ? ORDER BY Activo", new Object[] {  new Short(activo) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'impuesto = :impuesto'.
	 */
	public Producto[] findWhereImpuestoEquals(float impuesto) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE impuesto = ? ORDER BY impuesto", new Object[] {  new Float(impuesto) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'Categorias_ID_Categoria = :categoriasIdCategoria'.
	 */
	public Producto[] findWhereCategoriasIdCategoriaEquals(int categoriasIdCategoria) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Categorias_ID_Categoria = ? ORDER BY Categorias_ID_Categoria", new Object[] {  new Integer(categoriasIdCategoria) } );
	}

	/**
	 * Method 'ProductoDaoImpl'
	 * 
	 */
	public ProductoDaoImpl()
	{
	}

	/**
	 * Method 'ProductoDaoImpl'
	 * 
	 * @param userConn
	 */
	public ProductoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "akuavida.producto";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Producto fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Producto dto = new Producto();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Producto[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Producto dto = new Producto();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Producto ret[] = new Producto[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Producto dto, ResultSet rs) throws SQLException
	{
		dto.setIdProducto( rs.getString( COLUMN_ID_PRODUCTO ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setPrecio( rs.getFloat( COLUMN_PRECIO ) );
		dto.setImagen( super.getBlobColumn(rs, COLUMN_IMAGEN ) );
		dto.setDescripcion( rs.getString( COLUMN_DESCRIPCION ) );
		dto.setCantidad( rs.getInt( COLUMN_CANTIDAD ) );
		dto.setActivo( rs.getShort( COLUMN_ACTIVO ) );
		dto.setImpuesto( rs.getFloat( COLUMN_IMPUESTO ) );
		dto.setCategoriasIdCategoria( rs.getInt( COLUMN_CATEGORIAS_ID_CATEGORIA ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Producto dto)
	{
		dto.setIdProductoModified( false );
		dto.setNombreModified( false );
		dto.setPrecioModified( false );
		dto.setImagenModified( false );
		dto.setDescripcionModified( false );
		dto.setCantidadModified( false );
		dto.setActivoModified( false );
		dto.setImpuestoModified( false );
		dto.setCategoriasIdCategoriaModified( false );
	}

	/** 
	 * Returns all rows from the producto table that match the specified arbitrary SQL statement
	 */
	public Producto[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProductoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the producto table that match the specified arbitrary SQL statement
	 */
	public Producto[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProductoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
